version: '3.8'

services:
  arbitrage-bot:
    build: .
    container_name: arbitrage-bot
    restart: always
    volumes:
      - ./data:/data  # Для сохранения базы данных
      - .env:/app/.env:ro  # Конфигурация
    ports:
      - "8080:8080"  # Веб-интерфейс
    environment:
      - DB_PATH=/data/arbitrage.db
